apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: hello
  annotations:
    tekton.dev/tags: "konflux"
  labels:
    app.kubernetes.io/version: "0.1"
spec:
  description: |-
    Dummy task whose purpose is to:

    1. Make it easier to test the behavior of the scripts and workflows in this repo
    2. Provide an example of the repo layout that the workflows expect to operate on

  steps:
    - name: hello
      image: registry.access.redhat.com/ubi9/ubi-micro:9.6@sha256:f5c5213d2969b7b11a6666fc4b849d56b48d9d7979b60a37bb853dff0255c14b
      computeResources:
        requests:
          memory: 256Mi
          cpu: 100m
        limits:
          memory: 256Mi
      script: |
        #!/bin/bash

        echo "Hello there!" >> "$(workspaces.source.path)/source/hello.txt"

  workspaces:
    - name: source
      description: Workspace with the source code (at subpath /source)
