name: Run Go CI
"on":
  pull_request:
    branches: [main]
    paths:
      - "task-generator/**"
      - ".github/workflows/go-ci.yaml"
  merge_group:
    types: [checks_requested]

jobs:
  go:
    name: Check source code
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: task-generator/trusted-artifacts
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Install Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: task-generator/trusted-artifacts/go.mod
          cache-dependency-path: task-generator/trusted-artifacts/go.sum
      - name: Check go mod status
        run: |
          go mod tidy
          if [[ -n "$(git status -s)" ]]; then
            echo "Go module state is not clean:"
            git --no-pager diff
            exit 1
          fi
      - name: Check format
        run: |
          go fmt ./...
          if [[ -n "$(git status -s)" ]]; then
            echo "Go files are not properly formatted:"
            git --no-pager diff
            exit 1
          fi
      - name: Check lint
        uses: golangci/golangci-lint-action@1e7e51e771db61008b38414a730f564565cf7c20 # v9.2.0
        with:
          working-directory: task-generator/trusted-artifacts
          args: --timeout=10m
      - name: Run unit tests
        run: |
          go test ./...

  security_scan:
    name: Security scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Install Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: task-generator/trusted-artifacts/go.mod
          cache-dependency-path: task-generator/trusted-artifacts/go.sum
      # https://github.com/securego/gosec/blob/12be14859bc7d4b956b71bef0b443694aa519d8a/README.md#integrating-with-code-scanning
      - name: Run Gosec Security Scanner
        uses: securego/gosec@9e75c0576c9878035d4221392108d458abe10fc3 # v2.28.0
        with:
          # We let the report trigger content trigger a failure using the GitHub Security features.
          args: "-no-fail -fmt sarif -out results.sarif ./task-generator/trusted-artifacts/..."
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@5595ccaf912efad79be6eef63a5619ff05969be3 # v4.37.6
        with:
          sarif_file: results.sarif
