---
name: yamllint
"on":
  pull_request:
    branches: [main]
jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      - name: Lint YAML files
        run: |
          # --strict: exit with non-zero even for warnings
          hack/yamllint.sh --strict .
